services:
  # control:
  #   build: control
  #   ports:
  #     - 5000:8080
  #   environment:
  #     - CALCULATOR_URI=calculator:50052
  #     - KAFKA_URI=kafka:9092
  #   depends_on:
  #     - calculator
  #     - kafka

  calculator:
    build:
      context: calculator
      dockerfile: dockerfile
    ports:
      - 50052:50052
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017
      - GRPC_DNS_RESOLVER=native

  # producer:
  #   build:
  #     context: producer
  #   depends_on:
  #     - kafka
  #   environment:
  #     KAFKA_URI: kafka:9092

  kafka:
    image: docker.io/apache/kafka:latest
    ports:
      - 9092:9092
      - 29092:29092
    # environment:
    #   KAFKA_LISTENERS: PLAINTEXT://kafka:9092
    #   KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    #   KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    #   KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT

  mongo:
    image: docker.io/mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: docker.io/mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

networks:
  default:
    driver: bridge
