services:
  control:
    build: control
    ports:
       - 5000:8080
    environment:
       - CALCULATOR_URI=calculator:50052
       - KAFKA_URI=broker:29092
       - KAFKASERVICE_URI=http://kafkaservice:8084
    depends_on:
       - calculator
       - kafkaservice

  calculator:
    build:
      context: calculator
      dockerfile: dockerfile
    ports:
      - 50052:50052
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017
      - GRPC_DNS_RESOLVER=native
  
  kafkaservice:
    build:
      context: kafkaservice
      dockerfile: dockerfile
    ports:
      - 8084:8084
    depends_on:
      - broker
    environment:
      KAFKA_URI: broker:29092
  broker:
    image: apache/kafka:latest
    container_name: broker
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

  # producer:
  #   build:
  #     context: producer
  #   depends_on:
  #     - kafka
  #   environment:
  #     KAFKA_URI: kafka:9092

#  kafka:
 #   image: docker.io/apache/kafka:latest
  #  ports:
   #   - 9092:9092
    #  - 29092:29092
    # environment:
    #   KAFKA_LISTENERS: PLAINTEXT://kafka:9092
    #   KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    #   KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    #   KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT

  mongo:
    image: docker.io/mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: docker.io/mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

networks:
  default:
    driver: bridge
